name: Docs Build

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  docbuild:
    runs-on: linux.24_04.4x
    steps:
      - name: Checkout TorchX
        uses: actions/checkout@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: "3.12"
          enable-cache: true
      - name: Install Dependencies
        run: |
          set -eux
          uv sync --frozen --extra dev
          uv pip install -r docs/requirements.txt
      - name: Doc Test
        run: |
          cd docs
          uv run make doctest
      - name: Linkcheck
        run: |
          cd docs
          uv run make linkcheck
      - name: Doc Build
        run: |
          cd docs
          uv run make html
      - name: Coverage
        run: |
          set -ex
          cd docs
          uv run make coverage
          if [ "$(wc -l build/*/coverage/python.txt)" -ne 2 ]
          then
              cat build/*/coverage/python.txt
              echo "missing documentation coverage!"
              exit 1
          fi

  docpush:
    runs-on: linux.24_04.4x
    needs: docbuild
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout TorchX
        uses: actions/checkout@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: "3.12"
          enable-cache: true
      - name: Set Identity
        run: |
          set -ex
          git config --global user.email "runner@github.com"
          git config --global user.name "TorchX CI Runner"
      - name: Install Dependencies
        run: |
          set -eux
          uv sync --frozen --extra dev
          uv pip install -r docs/requirements.txt
      - name: Build
        run: |
          set -ex
          uv run docs/doc_push.sh --dry-run
      - name: Push
        run: |
          set -ex
          cd /tmp/torchx_docs_tmp/torchx_gh_pages
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
